print('{:10}{:10}'.format('hello', 'welcome'))
print('{:10}{:10}'.format('hello', 'welcome'))
print('{:10}{:10}'.format('hello', 'welcome'))
print('{:10}{:10}'.format('hello', 'welcome'))
print('{:10}{:10}'.format('hello', 'welcome'))
